[build]
  cmd = "templ generate && go build -o ./tmp/janitarr ./src"
  bin = "./tmp/janitarr dev"
  include_ext = ["go", "templ"]
  exclude_dir = ["tmp", "vendor", "node_modules", "src-ts", "ui-ts"]
  delay = 1000

[log]
  time = false

[misc]
  clean_on_exit = true
